//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by snu3.rc
//
#define IDD_PREFERENCES                 9
#define IDI_SNU3                        102
#define IDD_ENTERADDRESS                102
#define IDR_MENU1                       103
#define IDD_ADDEDITLINK                 103
#define IDD_SENDUPDATE                  104
#define IDD_DIALOG1                     105
#define IDD_LISTLINKS                   105
#define IDD_PREFS_LINKS                 106
#define IDR_ACCELERATOR1                108
#define IDR_ACCELERATOR                 108
#define IDD_PREFS_ABOUT                 109
#define IDD_LOGHARVESTER                111
#define IDD_SENDLOG                     113
#define IDD_PREFS_SETTINGS              114
#define IDD_GENERATEKEY                 115
#define IDD_SETPASSWORD                 116
#define IDD_ENTERPASSWORD               117
#define IDD_MESSAGEQUEUE                118
#define IDD_PREFS_MESSAGEQUEUE          119
#define IDD_PREFS_LOGHARVESTER          120
#define IDD_HTTPDOWNLOAD                121
#define IDD_STARTIRCBOT                 122
#define IDD_SPREAD_AIM                  123
#define IDD_PREFS_DISPLAY               124
#define IDD_CUSTOM_COMMAND              125
#define IDC_ADD                         1001
#define IDC_ADD2                        1002
#define IDC_REMOVE                      1002
#define IDC_GENERATE                    1002
#define IDC_TOTALITEMS                  1002
#define IDC_IMPORT                      1003
#define IDC_EXPORT                      1004
#define IDC_PERMANENT                   1004
#define IDC_CLEAR                       1005
#define IDC_IMPORT2                     1005
#define IDC_TREE                        1006
#define IDC_UPDATE                      1006
#define IDC_MAXLINKS                    1007
#define IDM_CLEARHISTORY                1007
#define IDC_AUTOADDLINKS                1008
#define IDC_EXECUTE                     1008
#define IDC_EDIT                        1009
#define IDC_URL                         1009
#define IDC_CLOSE                       1010
#define IDC_MINLINKS                    1010
#define IDC_ALLOWED                     1010
#define IDC_NEWMID                      1010
#define IDC_REGION                      1013
#define IDC_STATICUUID                  1013
#define IDC_STATICEXE                   1014
#define IDC_COLORBTN1                   1015
#define IDC_STATICMSG                   1015
#define IDC_COLORBTN2                   1016
#define IDC_STATICTTL                   1016
#define IDC_COLORBTN3                   1017
#define IDC_STATICADD                   1017
#define IDC_PORT                        1018
#define IDC_COLORBTN4                   1018
#define IDC_CUSTOMCOMMAND               1018
#define IDC_STATICMSGID                 1018
#define IDC_COLORBTN5                   1019
#define IDC_STATICSCRIPTNAME            1019
#define IDC_LIST                        1020
#define IDC_SEND                        1020
#define IDC_COLORBTN6                   1021
#define IDC_SIGN                        1021
#define IDC_COLORBTN8                   1022
#define IDC_STATIC_SIZE                 1022
#define IDC_SETTINGS                    1023
#define IDC_COLORBTN9                   1023
#define IDC_STATIC_DATE                 1023
#define IDC_LISTEN                      1024
#define IDC_COLORBTN7                   1024
#define IDC_STATIC_STATUS               1024
#define IDC_LIST1                       1025
#define IDC_MINIMIZETOTRAY              1026
#define IDC_SCRIPTNAME                  1027
#define IDC_KEYLOG                      1028
#define IDC_ADDNEW                      1028
#define IDC_FORMLOG                     1029
#define IDC_STATIC_BARTOP               1029
#define IDC_STATIC_BARBOTTOM            1031
#define IDC_HOST                        1032
#define IDC_STATICBG                    1032
#define IDC_EDIT3                       1033
#define IDC_DIRECTORY                   1033
#define IDC_HOST2                       1033
#define IDC_CHANNEL                     1033
#define IDC_TIMESTOSEND                 1033
#define IDC_ADDRESS                     1033
#define IDC_FILE                        1033
#define IDC_IDENT                       1034
#define IDC_NAME                        1035
#define IDC_AUTOREMOVELINKS             1036
#define IDC_COUNT                       1038
#define IDC_STATUS                      1042
#define IDC_BITS                        1043
#define IDC_STATUS2                     1043
#define IDC_PROGRESS                    1044
#define IDC_START                       1046
#define IDC_PASSWORD1                   1048
#define IDC_PASSWORD2                   1049
#define IDC_PASSWORD                    1049
#define IDC_CHECK                       1050
#define IDC_EXPORTPUBLIC                1054
#define IDC_EXECLIENTS                  1054
#define IDC_EXPORTPRIVATE               1055
#define IDC_EXELINKS                    1055
#define IDC_UUID                        1056
#define IDC_TTL                         1057
#define IDC_GROUP                       1058
#define IDC_MID                         1058
#define IDC_COMBO                       1059
#define IDC_AUTOSIGN                    1060
#define IDC_AUTOSEND                    1062
#define IDC_AUTOSENDONCONNECT           1063
#define IDC_EDIT1                       1064
#define IDC_SCRIPT                      1064
#define IDC_BROWSE                      1065
#define IDC_NICK                        1066
#define IDM_FILE                        40001
#define IDM_EXIT                        40002
#define IDM_TOOLS                       40002
#define IDM_HELP                        40003
#define ID_Menu40004                    40004
#define IDM_ABOUT                       40006
#define IDM_TOOLS_PREFERENCES           40007
#define ID_TEST_FART                    40009
#define ID_Menu                         40010
#define ID_FART                         40011
#define ID_COMMANDS_STARTIRC            40012
#define IDM_FILE_EXIT                   40012
#define ID_COMMANDS_STARTFTP            40013
#define IDM_HELP_ABOUT                  40013
#define ID_COMMANDS_STARTSOCKS5         40014
#define IDM_TOOLS_LOGHARVESTER          40014
#define ID_Menu40015                    40015
#define IDM_FILE_DISCONNECT             40016
#define IDM_TOOLS_LOG                   40017
#define IDM_FILE_CONNECT                40017
#define ID_SENDCOMMANDSTOLINKS          40018
#define ID_Menu40019                    40019
#define ID_FILE_CONNECT                 40020
#define IDM_CONNECT_ADDRESS             40020
#define IDM_TOOLS_MESSAGEQUEUE          40024
#define IDM_TOOLS_SENDUPDATE            40028
#define IDM_CONNECT_RANDOMLINK          40029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
